import type { Role } from '../../lib/types';

export type IlluType =
  | 'dashboard' | 'table' | 'form' | 'grades'
  | 'timetable' | 'consents' | 'plan' | 'evaluation'
  | 'banner' | 'profile';

export type NodeType = 'start' | 'step' | 'decision' | 'success' | 'reject';
export interface FNode { l: string; t: NodeType; }

export interface TModule {
  title: string;
  sub: string;
  accent: string;
  illu: IlluType;
  steps: string[];
  flow: FNode[];
  warn?: string;
  dos: string[];
  donts: string[];
}

/* ─── ADMIN ──────────────────────────────────────────────────── */
const ADMIN: TModule[] = [
  {
    title: 'Dashboard',
    sub: 'System-wide statistics and term health at a glance.',
    accent: '#7f1d2e', illu: 'dashboard',
    steps: ['Log in as Admin.', 'View stat cards: total students, faculty, courses, and active sections.', 'Check Active Term block — enrollment progress bars appear per section.', 'Review control window statuses before opening any term window.'],
    flow: [
      { l: 'Admin logs in', t: 'start' },
      { l: 'Dashboard loads', t: 'step' },
      { l: 'Active Term exists?', t: 'decision' },
      { l: 'View full stats & progress', t: 'success' },
      { l: 'Go to Term Control first', t: 'reject' },
    ],
    warn: 'All stats on this page are read-only. Changes must be made in their respective modules.',
    dos: ['Check the dashboard every start of term', 'Use enrollment bars to detect overloaded sections', 'Verify Active Term before opening any control window'],
    donts: ["Don't share admin login credentials", "Don't treat dashboard counts as official enrollment figures", "Don't ignore zero-enrollment warnings on active sections"],
  },
  {
    title: 'Dashboard Content',
    sub: 'Edit portal-wide announcements visible to all users.',
    accent: '#1e5c3a', illu: 'form',
    steps: ['Click Dashboard Content in the sidebar.', 'Edit the announcement text for each role (student, faculty, etc.).', 'Toggle visibility on/off per role type.', 'Click Save Changes — content goes live immediately.'],
    flow: [
      { l: 'Open Dashboard Content', t: 'start' },
      { l: 'Edit announcement text', t: 'step' },
      { l: 'Toggle role visibility', t: 'step' },
      { l: 'Click Save Changes', t: 'step' },
      { l: 'Announcement is live', t: 'success' },
    ],
    warn: 'Announcements are visible to ALL users of the selected role. Proofread before saving.',
    dos: ['Use announcements for term reminders and system notices', 'Toggle off roles that do not need the message', 'Save only after thorough review'],
    donts: ["Don't paste sensitive data (IDs, passwords) in announcements", "Don't leave stale announcements from past terms active", "Don't use announcements as a replacement for direct communication"],
  },
  {
    title: 'Term Control',
    sub: 'Create and activate terms; open and close control windows.',
    accent: '#7f1d2e', illu: 'form',
    steps: ['Go to Term Control → click Add Term.', 'Enter term name, academic year, and date range.', 'Click Set Active to make it the running term (only one can be active).', 'Open control windows: Enlistment, Enrollment, Grade Submission, Evaluation, and Prerogative.'],
    flow: [
      { l: 'Open Term Control', t: 'start' },
      { l: 'Add/select term', t: 'step' },
      { l: 'Set as Active Term', t: 'step' },
      { l: 'Open required windows', t: 'step' },
      { l: 'Term is running', t: 'success' },
    ],
    warn: 'Only ONE term can be active at a time. Setting a new active term closes the previous one.',
    dos: ['Open windows in the correct sequence: Enlistment → Enrollment → Grades', 'Close windows promptly when the period ends', 'Coordinate with OCS before opening/closing windows'],
    donts: ["Don't set a new active term while enrollment is still running", "Don't open Grade Submission before enrollment closes", "Don't delete a term that has enrolled students"],
  },
  {
    title: 'User Management',
    sub: 'Add, edit, import, and manage all portal accounts.',
    accent: '#1e5c3a', illu: 'table',
    steps: ['Click Add User. Fill in Last Name, First Name, Middle Name (optional), and Extension.', 'Set username, email, password, role, college, department, and program as applicable.', 'Click Save — user can log in immediately.', 'For bulk creation, download the CSV template, fill it in, and use Import CSV.'],
    flow: [
      { l: 'Open User Management', t: 'start' },
      { l: 'Single or bulk?', t: 'decision' },
      { l: 'Fill Add User form', t: 'step' },
      { l: 'Save user', t: 'success' },
      { l: 'Import CSV file', t: 'step' },
    ],
    warn: 'Deleting a user permanently removes all their data. Prefer disabling over deleting.',
    dos: ['Use the CSV template for bulk imports to avoid formatting errors', 'Assign the correct college/department/program before saving', 'Verify student numbers before saving'],
    donts: ["Don't delete users who have existing enrollment or grade records", "Don't reuse student numbers", "Don't set weak passwords for accounts"],
  },
  {
    title: 'Report Cards',
    sub: 'View and print student grade reports per term.',
    accent: '#7f1d2e', illu: 'grades',
    steps: ['Go to Report Cards.', 'Select the academic term from the dropdown.', 'Filter by college, department, or program as needed.', 'Click a student row to open and print their report card.'],
    flow: [
      { l: 'Open Report Cards', t: 'start' },
      { l: 'Select term', t: 'step' },
      { l: 'Filter by unit', t: 'step' },
      { l: 'Click student row', t: 'step' },
      { l: 'Print/export report card', t: 'success' },
    ],
    warn: 'Report cards display only finalized grades. INC and missing grades will show as blank.',
    dos: ['Export report cards only after grades are fully submitted', 'Filter by department for faster lookups', 'Print as PDF for archiving'],
    donts: ["Don't share report cards without student consent", "Don't print report cards before grade submission closes", "Don't use report card data for unofficial communications"],
  },
  {
    title: 'Academic Units',
    sub: 'Manage colleges, departments, and degree programs.',
    accent: '#1e5c3a', illu: 'table',
    steps: ['Add Colleges first (e.g., College of Engineering).', 'Add Departments linked to the correct college.', 'Add Programs (degree programs) linked to the correct department.', 'Edit or delete units using row action icons — all must exist before adding users.'],
    flow: [
      { l: 'Open Academic Units', t: 'start' },
      { l: 'Add College', t: 'step' },
      { l: 'Add Department', t: 'step' },
      { l: 'Add Program', t: 'step' },
      { l: 'Units ready for use', t: 'success' },
    ],
    warn: 'Colleges must be created BEFORE departments, and departments BEFORE programs.',
    dos: ['Follow the hierarchy: College → Department → Program', 'Use consistent naming conventions', 'Create all units before creating users'],
    donts: ["Don't delete units that have existing users or courses assigned", "Don't skip levels (e.g., Program without a Department)", "Don't use abbreviations inconsistently in unit names"],
  },
  {
    title: 'Rooms',
    sub: 'Add and manage classrooms and laboratories.',
    accent: '#7f1d2e', illu: 'form',
    steps: ['Click Add Room.', 'Enter the room name/code and seating capacity.', 'Select room type: Lecture, Laboratory, or Special.', 'Click Save — the room is now available when OCS creates sections.'],
    flow: [
      { l: 'Open Rooms', t: 'start' },
      { l: 'Click Add Room', t: 'step' },
      { l: 'Enter details & type', t: 'step' },
      { l: 'Save room', t: 'step' },
      { l: 'Available for scheduling', t: 'success' },
    ],
    warn: 'Rooms with active sections cannot be deleted during the current term.',
    dos: ['Add all rooms before the term starts', 'Set accurate seating capacity for slot management', 'Use standard room codes (e.g., GH-201)'],
    donts: ["Don't delete rooms that are assigned to active sections", "Don't enter incorrect capacity — it affects enrollment limits", "Don't use the same room code twice"],
  },
  {
    title: 'Password Tickets',
    sub: 'Review and resolve user password reset requests.',
    accent: '#1e5c3a', illu: 'table',
    steps: ['Go to Password Tickets to see all open requests.', 'Click a ticket and read the user\'s identity verification answer.', 'Verify the answer matches the user\'s profile data.', 'Click Resolve, enter a temporary password, and inform the user to change it on next login.'],
    flow: [
      { l: 'Ticket submitted by user', t: 'start' },
      { l: 'Admin reviews request', t: 'step' },
      { l: 'Identity verified?', t: 'decision' },
      { l: 'Resolve with temp password', t: 'success' },
      { l: 'Reject — ask for re-submission', t: 'reject' },
    ],
    warn: 'Never issue a reset without proper identity verification. Anyone can submit a ticket.',
    dos: ['Always verify the identity answer before resolving', 'Set strong temporary passwords', 'Inform users to change their password immediately after reset'],
    donts: ["Don't resolve tickets without verification", "Don't reuse previous passwords as temporary ones", "Don't leave open tickets unresolved for more than 24 hours"],
  },
  {
    title: 'Graduation Settings',
    sub: 'Set GWA thresholds, required units, and honors bands.',
    accent: '#7f1d2e', illu: 'form',
    steps: ['Go to Graduation Settings.', 'Set minimum GWA for graduation eligibility.', 'Set the minimum total units required to graduate.', 'Configure honors bands: Summa, Magna, and Cum Laude GWA ranges. Click Save.'],
    flow: [
      { l: 'Open Graduation Settings', t: 'start' },
      { l: 'Set GWA threshold', t: 'step' },
      { l: 'Set required units', t: 'step' },
      { l: 'Set honors bands', t: 'step' },
      { l: 'Save settings', t: 'success' },
    ],
    warn: 'Changes to graduation settings affect ALL future graduation evaluations. Coordinate with the Registrar.',
    dos: ['Confirm settings with the Registrar before saving', 'Set honors bands according to institutional policy', 'Test settings on a sample student record after saving'],
    donts: ["Don't change GWA thresholds mid-term when graduation applications are pending", "Don't set overlapping GWA ranges for honors bands", "Don't leave default values unconfigured"],
  },
  {
    title: 'Portal Settings',
    sub: 'Customize portal name, logo, and global feature flags.',
    accent: '#1e5c3a', illu: 'form',
    steps: ['Go to Portal Settings.', 'Enter Portal Name, Institution Name, and Tagline.', 'Upload a logo image (PNG recommended, max 2MB).', 'Toggle global feature flags. Click Save Settings.'],
    flow: [
      { l: 'Open Portal Settings', t: 'start' },
      { l: 'Edit name & branding', t: 'step' },
      { l: 'Upload logo', t: 'step' },
      { l: 'Toggle feature flags', t: 'step' },
      { l: 'Save settings', t: 'success' },
    ],
    warn: 'Portal name and logo are visible on the login page immediately after saving.',
    dos: ['Use high-resolution logos for best display quality', 'Keep the portal name concise and official', 'Test the login page after saving branding changes'],
    donts: ["Don't upload copyrighted images not owned by the institution", "Don't disable features that users are actively using mid-term", "Don't use informal names in the portal name field"],
  },
];

/* ─── OCS ────────────────────────────────────────────────────── */
const OCS: TModule[] = [
  {
    title: 'Dashboard',
    sub: 'College-wide overview of sections, consents, and enrollment.',
    accent: '#1e5c3a', illu: 'dashboard',
    steps: ['Log in as OCS Staff.', 'View college stats: courses, sections, students, pending consents.', 'Check the Pending OCS Consents panel — act on these first.', 'Review the Active Term Sections enrollment progress.'],
    flow: [
      { l: 'OCS logs in', t: 'start' },
      { l: 'Dashboard loads', t: 'step' },
      { l: 'Pending consents?', t: 'decision' },
      { l: 'Process consents', t: 'step' },
      { l: 'Monitor enrollment', t: 'success' },
    ],
    warn: 'Unacted consent requests block students from enlisting. Check the dashboard daily during enlistment.',
    dos: ['Process pending consents within 24 hours', 'Check enrollment progress against section capacity', 'Monitor for overloaded sections and report to Admin'],
    donts: ["Don't ignore low-enrollment warnings — sections may need to be dissolved", "Don't approve consents for sections that are already full", "Don't access other colleges' records"],
  },
  {
    title: 'Course Overview',
    sub: 'Read-only view of all sections and enrollment for the active term.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['Go to Course Overview.', 'Use the search bar to filter by course code, title, or faculty name.', 'View enrollment count vs. max capacity for each section.', 'Click a section row to see the full enrolled student list.'],
    flow: [
      { l: 'Open Course Overview', t: 'start' },
      { l: 'Search/filter sections', t: 'step' },
      { l: 'Review enrollment counts', t: 'step' },
      { l: 'Click section for details', t: 'step' },
      { l: 'View student roster', t: 'success' },
    ],
    warn: 'This is a view-only page. To make changes, use the Sections or Grade & Enrollment modules.',
    dos: ['Use this page for quick monitoring during enlistment', 'Export section data for reporting purposes', 'Identify under-enrolled sections early for possible dissolution'],
    donts: ["Don't try to edit data from this page — use dedicated modules instead", "Don't share enrollment counts publicly before the official census date", "Don't confuse Course Overview with Grade & Enrollment"],
  },
  {
    title: 'Courses',
    sub: 'Add and manage courses for your college.',
    accent: '#1e5c3a', illu: 'form',
    steps: ['Click Add Course.', 'Fill in: code, type (lecture/lab), title, units, and year level.', 'Set consent flags: COI (requires instructor consent), Dept Consent, OCS Consent.', 'Add prerequisites and corequisites if applicable. Click Save.'],
    flow: [
      { l: 'Open Courses', t: 'start' },
      { l: 'Click Add Course', t: 'step' },
      { l: 'Fill details & consents', t: 'step' },
      { l: 'Add pre/co-requisites', t: 'step' },
      { l: 'Save course', t: 'success' },
    ],
    warn: 'Courses cannot be deleted once they have sections or enrolled students attached to them.',
    dos: ['Use the official course code from the curriculum', 'Set consent flags based on faculty or department policy', 'Always set prerequisite courses to enforce academic progression'],
    donts: ["Don't create duplicate course codes", "Don't change course units after students have enrolled", "Don't leave year level blank — it affects plan of study matching"],
  },
  {
    title: 'Sections',
    sub: 'Create sections for the active term with schedule and faculty.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['An Active Term must exist first (check Term Control).', 'Click Add Section → select the course.', 'Assign a faculty member, set schedule (days/time/room), and max slots.', 'Click Save — the section is now available for student enlistment.'],
    flow: [
      { l: 'Open Sections', t: 'start' },
      { l: 'Active term exists?', t: 'decision' },
      { l: 'Click Add Section', t: 'step' },
      { l: 'Set faculty, schedule, slots', t: 'step' },
      { l: 'Section ready for enlistment', t: 'success' },
    ],
    warn: 'Schedule conflicts for rooms or faculty are not automatically detected. Verify manually.',
    dos: ['Assign faculty before publishing sections', 'Set realistic max slots based on room capacity', 'Coordinate schedules with faculty and department heads'],
    donts: ["Don't create sections without assigning a room", "Don't set max slots higher than room capacity", "Don't delete sections once students have enlisted"],
  },
  {
    title: 'OCS Consents',
    sub: 'Review and approve OCS consent requests from students.',
    accent: '#1e5c3a', illu: 'consents',
    steps: ['Go to OCS Consents to see all pending requests.', 'Click a request to view student details, target course, and stated reason.', 'Click Approve to allow the student to enlist.', 'Click Deny if the request is invalid — provide a reason.'],
    flow: [
      { l: 'Student submits OCS consent', t: 'start' },
      { l: 'OCS reviews request', t: 'step' },
      { l: 'Valid reason & slot available?', t: 'decision' },
      { l: 'Approve → student can enlist', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'Approving a consent does NOT automatically enlist the student. They must enlist themselves.',
    dos: ['Review each request carefully before deciding', 'Approve promptly to avoid delaying student enrollment', 'Deny with clear reasons so students can appeal if needed'],
    donts: ["Don't approve consents for sections that have no available slots", "Don't approve without reviewing the student's academic standing", "Don't leave requests pending beyond the enlistment window"],
  },
  {
    title: 'Students',
    sub: 'View academic records for students in your college.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['Go to Students. Search by name, student number, or program.', 'Click a student row to open their academic record.', 'View enrollment history, grades per term, GWA, and plan of study completion.', 'Export TOR or grade summary as needed.'],
    flow: [
      { l: 'Open Students', t: 'start' },
      { l: 'Search for student', t: 'step' },
      { l: 'Click student record', t: 'step' },
      { l: 'Review academic data', t: 'step' },
      { l: 'Export if needed', t: 'success' },
    ],
    warn: 'Student records are confidential. Only access records for official academic purposes.',
    dos: ['Use search filters to find students quickly', 'Review TOR data before certifying records', 'Export records only for official use'],
    donts: ["Don't share student records with unauthorized individuals", "Don't modify records outside of Grade & Enrollment module", "Don't access records of students not in your college"],
  },
  {
    title: 'Grade & Enrollment',
    sub: 'Override grades and manually manage student enrollment.',
    accent: '#1e5c3a', illu: 'grades',
    steps: ['Select a term and section from the dropdowns.', 'To override a grade: click the grade cell, enter the corrected grade, and save with a justification note.', 'To manually enroll: click Add Enrollment → search the student → select the section.', 'To drop: locate the enrollment row → click Drop → confirm the action.'],
    flow: [
      { l: 'Open Grade & Enrollment', t: 'start' },
      { l: 'Select term & section', t: 'step' },
      { l: 'Override or enroll?', t: 'decision' },
      { l: 'Edit grade with justification', t: 'success' },
      { l: 'Add/drop enrollment', t: 'success' },
    ],
    warn: 'All grade overrides are permanently logged. They can be audited by the Registrar.',
    dos: ['Always enter a justification reason for grade overrides', 'Verify student identity before manual enrollment', 'Coordinate with faculty before changing submitted grades'],
    donts: ["Don't override grades without faculty knowledge", "Don't manually enroll students who are not officially registered", "Don't drop active enrollments without student request or valid reason"],
  },
  {
    title: 'Plan of Study',
    sub: 'Configure required courses per degree program.',
    accent: '#7f1d2e', illu: 'plan',
    steps: ['Select a Degree Program from the dropdown.', 'Add required courses for each year level and semester.', 'Mark each course as required or elective.', 'Save — students in this program can now track their plan of study.'],
    flow: [
      { l: 'Open Plan of Study', t: 'start' },
      { l: 'Select degree program', t: 'step' },
      { l: 'Add courses by year/sem', t: 'step' },
      { l: 'Mark required/elective', t: 'step' },
      { l: 'Plan published', t: 'success' },
    ],
    warn: 'Changes to the plan of study affect all students currently enrolled in that program.',
    dos: ['Map courses exactly as in the official curriculum', 'Mark electives clearly to give students flexibility', 'Update the plan when the curriculum is revised'],
    donts: ["Don't delete required courses from the plan if students are currently taking them", "Don't leave year levels blank — students rely on this for graduation tracking", "Don't create plans without referencing the official program curriculum"],
  },
  {
    title: 'Specialization',
    sub: 'Review and decide on student specialization track applications.',
    accent: '#1e5c3a', illu: 'consents',
    steps: ['Go to Specialization to see pending applications.', 'Click an application to review the proposed track and course plan.', 'Verify the student meets prerequisites for the chosen specialization.', 'Approve or Deny with detailed remarks.'],
    flow: [
      { l: 'Student applies for specialization', t: 'start' },
      { l: 'OCS reviews application', t: 'step' },
      { l: 'Prerequisites met?', t: 'decision' },
      { l: 'Approve specialization', t: 'success' },
      { l: 'Deny with remarks', t: 'reject' },
    ],
    warn: 'Approving a specialization locks the student into a specific course track. This is difficult to reverse.',
    dos: ['Review the student\'s current grades before approving', 'Check that the specialization has available sections', 'Provide clear feedback when denying'],
    donts: ["Don't approve specializations without prerequisite verification", "Don't deny without giving students actionable feedback", "Don't approve for specializations with no open sections"],
  },
  {
    title: 'Graduation Applications',
    sub: 'Process and decide on student graduation applications.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['Go to Graduation Applications to see all pending applications.', 'Click an application to review GWA, total units, and course completion status.', 'Cross-check against Graduation Settings (min GWA, required units).', 'Click Approve or Deny with remarks.'],
    flow: [
      { l: 'Student submits application', t: 'start' },
      { l: 'OCS reviews records', t: 'step' },
      { l: 'GWA & units met?', t: 'decision' },
      { l: 'Approve graduation', t: 'success' },
      { l: 'Deny with missing reqs', t: 'reject' },
    ],
    warn: 'Approved graduation applications are forwarded to the Registrar. Double-check before approving.',
    dos: ['Verify GWA and unit completion against Graduation Settings', 'Check that no INC grades remain unresolved', 'Approve in batches only after reviewing each record'],
    donts: ["Don't approve applications with unresolved INC grades", "Don't deny without listing specific missing requirements", "Don't process graduation applications without confirming the official ceremony date"],
  },
  {
    title: 'Reconsideration',
    sub: 'Handle student grade appeal requests.',
    accent: '#1e5c3a', illu: 'consents',
    steps: ['Go to Reconsideration to see pending grade appeal requests.', 'Click a request to read the student\'s reason for the appeal.', 'Coordinate with the faculty member to verify the grade.', 'Approve (update the grade) or Deny with a clear reason.'],
    flow: [
      { l: 'Student submits appeal', t: 'start' },
      { l: 'OCS reviews reason', t: 'step' },
      { l: 'Coordinate with faculty', t: 'step' },
      { l: 'Grade error confirmed?', t: 'decision' },
      { l: 'Approve & update grade', t: 'success' },
    ],
    warn: 'All approved grade reconsiderations are permanently logged and auditable.',
    dos: ['Always contact the faculty before approving any grade change', 'Document the reason for every decision', 'Process appeals within the published reconsideration window'],
    donts: ["Don't approve grade changes without faculty confirmation", "Don't deny legitimate appeals without investigation", "Don't process reconsiderations after the official window closes"],
  },
  {
    title: 'Change & Drop',
    sub: 'Process change-section and drop-subject requests.',
    accent: '#7f1d2e', illu: 'consents',
    steps: ['Go to Change & Drop to see all pending requests.', 'For Change: verify the requested new section has available slots.', 'For Drop: confirm the change/drop window is still open.', 'Approve → enrollment is updated; Deny with reason if requirements are not met.'],
    flow: [
      { l: 'Student submits request', t: 'start' },
      { l: 'OCS reviews type', t: 'step' },
      { l: 'Requirements met?', t: 'decision' },
      { l: 'Approve & update enrollment', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'All changes and drops are permanent once approved. Confirm with the student before acting.',
    dos: ['Check slot availability before approving change requests', 'Confirm the window is open before processing drops', 'Notify the student after processing'],
    donts: ["Don't approve changes to full sections", "Don't process requests after the change/drop window closes", "Don't drop enrollments without student-initiated written request"],
  },
  {
    title: 'Appeal to Enlist (PD)',
    sub: 'Review appeals from permanently disqualified students.',
    accent: '#7f1d2e', illu: 'banner',
    steps: ['Go to Banner Requests → PD Appeal queue.', 'Review the student\'s academic history, grounds for appeal, and attached documents.', 'Consult with the Dean or Registrar per institutional policy.', 'Approve (manually enroll) or Deny with a fully documented reason.'],
    flow: [
      { l: 'Student submits PD appeal', t: 'start' },
      { l: 'OCS reviews history & docs', t: 'step' },
      { l: 'Consult Dean/Registrar', t: 'step' },
      { l: 'Appeal granted?', t: 'decision' },
      { l: 'Manually enroll student', t: 'success' },
    ],
    warn: 'PD appeals carry serious academic implications. Never approve without institutional authority sign-off.',
    dos: ['Require complete documentation before processing', 'Consult Dean and Registrar before deciding', 'Document every step of the review process'],
    donts: ["Don't approve PD appeals unilaterally without Dean/Registrar approval", "Don't process appeals with incomplete or unverified documents", "Don't notify the student of the outcome before official confirmation from authorities"],
  },
  {
    title: 'Request for Late Enrollment',
    sub: 'Process late enrollment requests within the allowed window.',
    accent: '#1e5c3a', illu: 'banner',
    steps: ['Go to Banner Requests → Late Enrollment queue.', 'Verify the stated reason (medical, emergency, etc.) and review supporting documents.', 'Confirm the requested sections have available slots.', 'Approve (enroll + note late fee) or Deny with reason.'],
    flow: [
      { l: 'Student submits request', t: 'start' },
      { l: 'OCS reviews reason & docs', t: 'step' },
      { l: 'Slots available & reason valid?', t: 'decision' },
      { l: 'Approve & process enrollment', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'Late enrollment requests cannot be processed after the late enrollment window has closed.',
    dos: ['Verify supporting documents for legitimacy', 'Confirm slot availability before approval', 'Note applicable late fees when approving'],
    donts: ["Don't approve without valid supporting documents", "Don't process late enrollments after the official late window closes", "Don't waive late fees without proper authorization"],
  },
  {
    title: 'Change / Add / Drop (DRP)',
    sub: 'Process formal change, add, and drop subject requests.',
    accent: '#92400e', illu: 'banner',
    steps: ['Go to Banner Requests → Change/Add/Drop queue.', 'Identify the request type: Change section, Add subject, or Drop subject.', 'Verify slot availability and confirm the window is open.', 'Approve → enrollment updated; for drops, a DRP grade is recorded on the TOR.'],
    flow: [
      { l: 'Request received', t: 'start' },
      { l: 'Identify request type', t: 'step' },
      { l: 'Requirements met?', t: 'decision' },
      { l: 'Approve & record DRP', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'DRP grades are permanently recorded on the student\'s TOR. Double-check before approving drop requests.',
    dos: ['Verify window status before processing any request', 'Confirm slot availability for change/add requests', 'Explain the DRP grade implications to students before dropping'],
    donts: ["Don't approve drops without student-initiated written request", "Don't process requests outside the official window", "Don't ignore change requests that could affect room capacity"],
  },
];

/* ─── FACULTY ────────────────────────────────────────────────── */
const FACULTY: TModule[] = [
  {
    title: 'Dashboard',
    sub: 'Your teaching overview for the current active term.',
    accent: '#1d4ed8', illu: 'dashboard',
    steps: ['Log in as Faculty.', 'View stat cards: active sections, total students, evaluation rating, grades submitted.', 'Check My Classes panel for a quick view of assigned sections.', 'Review Student Evaluation summary for this term.'],
    flow: [
      { l: 'Faculty logs in', t: 'start' },
      { l: 'Dashboard loads', t: 'step' },
      { l: 'Check active sections', t: 'step' },
      { l: 'Review eval ratings', t: 'step' },
      { l: 'Navigate to needed module', t: 'success' },
    ],
    warn: 'Dashboard stats update in real time. Evaluation ratings are visible only AFTER the FIC window closes.',
    dos: ['Check the dashboard at the start of each class day', 'Monitor evaluation ratings each term for self-improvement', 'Verify grade submission status before the deadline'],
    donts: ["Don't assume grade submission is complete based on the dashboard alone — verify in Grade Encoding", "Don't ignore missing evaluation data — follow up with students", "Don't share your dashboard view with students"],
  },
  {
    title: 'My Classes',
    sub: 'View your assigned class rosters for the active term.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['Go to My Classes.', 'Click on a section to expand the full student roster.', 'View student names, student numbers, and enrollment status.', 'Use Export to download the class list as a CSV file.'],
    flow: [
      { l: 'Open My Classes', t: 'start' },
      { l: 'View section list', t: 'step' },
      { l: 'Click section', t: 'step' },
      { l: 'View full roster', t: 'step' },
      { l: 'Export if needed', t: 'success' },
    ],
    warn: 'Class rosters reflect only officially enrolled students. Enlisting students are not included until enrollment is confirmed.',
    dos: ['Download the roster at the start of the term for your records', 'Check for newly enrolled students after the enrollment window opens', 'Verify student count matches your expected class size'],
    donts: ["Don't use rosters as attendance sheets without official confirmation", "Don't share class lists with third parties", "Don't manually track students outside the portal system"],
  },
  {
    title: 'My Timetable',
    sub: 'Weekly teaching schedule for the active term.',
    accent: '#1d4ed8', illu: 'timetable',
    steps: ['Go to My Timetable.', 'View the weekly grid layout from Monday to Saturday.', 'Colored blocks represent your assigned sections with time, day, and room.', 'Click any block to see course code, section ID, room, and enrolled student count.'],
    flow: [
      { l: 'Open My Timetable', t: 'start' },
      { l: 'View weekly grid', t: 'step' },
      { l: 'Spot time slots & rooms', t: 'step' },
      { l: 'Click block for details', t: 'step' },
      { l: 'Plan teaching schedule', t: 'success' },
    ],
    warn: 'Timetable is read-only. Contact OCS if there are scheduling conflicts or errors.',
    dos: ['Review your timetable at the start of every term', 'Note room assignments to avoid wrong venue errors', 'Cross-check with room bookings for lab sections'],
    donts: ["Don't teach in a different room without notifying OCS", "Don't ignore scheduling conflicts — report them immediately", "Don't use the timetable as your only source of truth for schedule changes"],
  },
  {
    title: 'Grade Encoding',
    sub: 'Encode and submit student grades when the window is open.',
    accent: '#7f1d2e', illu: 'grades',
    steps: ['Verify the Grade Submission window is OPEN (check Dashboard).', 'Select the section from the dropdown.', 'Enter grades: 1.0–3.0, 5.0 (failed), INC (incomplete), DRP (dropped), S/U.', 'Review all entries carefully, then click Submit Grades and confirm.'],
    flow: [
      { l: 'Grade Submission opens', t: 'start' },
      { l: 'Select section', t: 'step' },
      { l: 'Enter all grades', t: 'step' },
      { l: 'All grades entered?', t: 'decision' },
      { l: 'Submit & confirm', t: 'success' },
    ],
    warn: 'Submitted grades are FINAL. Any corrections require an OCS-approved override with full justification.',
    dos: ['Double-check every grade before clicking Submit', 'Submit well before the deadline — the window closes automatically', 'Use INC only for students with incomplete requirements, not failing grades'],
    donts: ["Don't submit grades after the deadline", "Don't leave any grade cells blank", "Don't use INC as a substitute for a failing grade (5.0)"],
  },
  {
    title: 'Prerogatives',
    sub: 'Approve or deny student prerogative requests for your sections.',
    accent: '#1d4ed8', illu: 'consents',
    steps: ['Go to Prerogatives when the prerogative window is open.', 'Click a request to view student details and their stated reason.', 'Check if the section still has available slots.', 'Click Approve to enlist the student, or Deny if the section is full or the request is invalid.'],
    flow: [
      { l: 'Student submits prerogative', t: 'start' },
      { l: 'Faculty reviews request', t: 'step' },
      { l: 'Slots available & valid?', t: 'decision' },
      { l: 'Approve → student enlisted', t: 'success' },
      { l: 'Deny request', t: 'reject' },
    ],
    warn: 'Approving a prerogative for a full section may exceed the official room capacity. Check with OCS first.',
    dos: ['Review the student\'s reason and academic standing before deciding', 'Approve promptly — the prerogative window is short', 'Deny with a reason so the student can seek alternatives'],
    donts: ["Don't approve for sections beyond room capacity", "Don't approve prerogatives after the official window closes", "Don't leave requests pending — unanswered requests expire and block students"],
  },
  {
    title: 'Consents (COI)',
    sub: 'Review Consent of Instructor requests for your courses.',
    accent: '#7f1d2e', illu: 'consents',
    steps: ['Go to Consents to see pending COI requests for your sections.', 'Click a request to see the student\'s name, target section, and reason.', 'Verify if the student meets any informal course requirements.', 'Click Approve to allow enlistment, or Deny with a clear reason.'],
    flow: [
      { l: 'Student requests COI', t: 'start' },
      { l: 'Faculty reviews request', t: 'step' },
      { l: 'Student meets criteria?', t: 'decision' },
      { l: 'Approve → student can enlist', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'COI approval does not enlist the student. They must enlist themselves after receiving your approval.',
    dos: ['Review COI requests during the enlistment period', 'Approve students who have legitimate need and meet criteria', 'Deny clearly and direct students to alternatives if needed'],
    donts: ["Don't approve COI for sections you didn't set the consent flag on", "Don't deny COI requests without reason — students have the right to appeal", "Don't approve after the enlistment window closes"],
  },
  {
    title: 'Removal / Completion',
    sub: 'Resolve INC (Incomplete) grades when the removal window opens.',
    accent: '#1d4ed8', illu: 'grades',
    steps: ['Wait for the Removal/Completion window to open (check Dashboard).', 'Find the student with an INC grade in your class list.', 'Enter the removal exam score or completion grade.', 'Click Save — the system computes and records the final grade.'],
    flow: [
      { l: 'Removal window opens', t: 'start' },
      { l: 'Find INC-graded student', t: 'step' },
      { l: 'Student submitted requirements?', t: 'decision' },
      { l: 'Enter & save final grade', t: 'success' },
      { l: 'INC remains if no submission', t: 'reject' },
    ],
    warn: 'Unresolved INC grades after the removal window become 5.0 (Failed) by policy in most institutions.',
    dos: ['Inform students of removal requirements before the window opens', 'Submit removal grades within the window period', 'Verify the computed final grade before saving'],
    donts: ["Don't wait for students to remind you — proactively process INC grades", "Don't submit a removal grade after the window closes", "Don't convert INC to a passing grade without actual completion of requirements"],
  },
  {
    title: 'Student Evaluations',
    sub: 'View aggregated evaluation scores from your students.',
    accent: '#7f1d2e', illu: 'evaluation',
    steps: ['Results are visible ONLY after the FIC (Faculty-in-Charge) window closes.', 'Select the term from the dropdown to view that term\'s results.', 'Review overall average rating and per-question breakdowns.', 'Check response rate and per-section scores for deeper insight.'],
    flow: [
      { l: 'FIC window closes', t: 'start' },
      { l: 'Admin releases results', t: 'step' },
      { l: 'Faculty opens Evaluations', t: 'step' },
      { l: 'Select term', t: 'step' },
      { l: 'Review ratings per section', t: 'success' },
    ],
    warn: 'Evaluation results are confidential. Individual student responses are anonymous and must not be traced.',
    dos: ['Use evaluation data to improve your teaching methods', 'Compare results across terms to identify trends', 'Discuss results with your department head if needed'],
    donts: ["Don't try to identify which student submitted a specific evaluation", "Don't use low ratings to penalize students", "Don't share your evaluation results publicly without proper authorization"],
  },
];

/* ─── STUDENT ────────────────────────────────────────────────── */
const STUDENT: TModule[] = [
  {
    title: 'Dashboard',
    sub: 'Your personal academic overview for the active term.',
    accent: '#92400e', illu: 'dashboard',
    steps: ['Log in as a student.', 'View enrolled subjects, pending evaluations, GWA, and pending consents.', 'Check the Current Enrollment list for your official subjects this term.', 'Review the Grade Status notice to know if grades are currently viewable.'],
    flow: [
      { l: 'Student logs in', t: 'start' },
      { l: 'Dashboard loads', t: 'step' },
      { l: 'Check enrollment status', t: 'step' },
      { l: 'Pending evaluations?', t: 'decision' },
      { l: 'Complete SET to unlock grades', t: 'step' },
    ],
    warn: 'Grades are LOCKED until you complete all faculty evaluations (SET module). This is enforced system-wide.',
    dos: ['Check the dashboard every day during term windows', 'Complete SET evaluations as soon as the window opens', 'Monitor your GWA and enrollment status regularly'],
    donts: ["Don't skip SET evaluations — grades remain locked until completed", "Don't ignore pending consent notifications", "Don't assume enrollment is confirmed without checking this page"],
  },
  {
    title: 'Enlistment',
    sub: 'Enlist in course sections when the enlistment window is open.',
    accent: '#7f1d2e', illu: 'table',
    steps: ['Wait for the Enlistment window to open (visible on Dashboard).', 'Browse sections — filter by department, course code, or time slot.', 'Obtain required consents (COI/Dept/OCS) via My Consents BEFORE enlisting.', 'Add sections to your cart, check for schedule conflicts, then click Submit Enlistment.'],
    flow: [
      { l: 'Enlistment window opens', t: 'start' },
      { l: 'Obtain required consents', t: 'step' },
      { l: 'Browse and add sections', t: 'step' },
      { l: 'Any schedule conflicts?', t: 'decision' },
      { l: 'Submit enlistment', t: 'success' },
    ],
    warn: 'Enlistment is NOT enrollment. You must also complete enrollment within the enrollment window.',
    dos: ['Secure all required consents before the enlistment window opens', 'Check section capacity before enlisting', 'Resolve schedule conflicts before submitting'],
    donts: ["Don't enlist in sections that conflict with your schedule", "Don't wait until the last day — popular sections fill up fast", "Don't mistake enlistment for enrollment"],
  },
  {
    title: 'Prerogatives',
    sub: 'Request enrollment in full or restricted sections via faculty approval.',
    accent: '#92400e', illu: 'consents',
    steps: ['Go to Prerogatives when the prerogative window is open.', 'Search for the target section you want to join.', 'Click Request Prerogative and enter a clear, convincing reason.', 'Wait for the faculty decision — track your request status here.'],
    flow: [
      { l: 'Prerogative window opens', t: 'start' },
      { l: 'Find target section', t: 'step' },
      { l: 'Submit request with reason', t: 'step' },
      { l: 'Faculty reviews request', t: 'step' },
      { l: 'Approved → enrolled', t: 'success' },
    ],
    warn: 'Prerogative requests are not guaranteed. Faculty can deny without detailed explanation.',
    dos: ['Write a clear and professional reason for your request', 'Submit requests early — faculty may take time to respond', 'Have a backup section in mind in case of denial'],
    donts: ["Don't submit frivolous prerogative requests", "Don't request prerogatives for sections you have no genuine need for", "Don't submit a prerogative after the window closes"],
  },
  {
    title: 'My Consents',
    sub: 'Request and track COI, Dept, and OCS consent statuses.',
    accent: '#7f1d2e', illu: 'consents',
    steps: ['Go to My Consents to see all your existing requests and their statuses.', 'Click Request Consent → select the section and consent type.', 'COI goes to Faculty, Dept goes to Dept Head, OCS goes to OCS staff.', 'Once Approved, proceed to Enlistment to use the consent.'],
    flow: [
      { l: 'Open My Consents', t: 'start' },
      { l: 'Click Request Consent', t: 'step' },
      { l: 'Select type & section', t: 'step' },
      { l: 'Wait for approval', t: 'step' },
      { l: 'Approved → enlist', t: 'success' },
    ],
    warn: 'Consent approval does NOT auto-enlist you. You must still enlist the subject in the Enlistment module.',
    dos: ['Request consents BEFORE the enlistment window opens', 'Follow up with faculty/OCS if a consent is pending for too long', 'Keep track of which sections require which type of consent'],
    donts: ["Don't request a consent and forget to enlist", "Don't submit multiple consent requests for the same section", "Don't wait until the last minute to request consents"],
  },
  {
    title: 'My Grades',
    sub: 'View your grades after completing all faculty evaluations.',
    accent: '#92400e', illu: 'grades',
    steps: ['Complete ALL faculty evaluations in the SET module first.', 'Go to My Grades — grades unlock after evaluations AND after admin enables grade viewing.', 'Select the term from the dropdown to view grades for that term.', 'View per-subject grades, term GWA, and cumulative GWA.'],
    flow: [
      { l: 'Submit all SET evaluations', t: 'start' },
      { l: 'Admin enables grade view', t: 'step' },
      { l: 'Open My Grades', t: 'step' },
      { l: 'Select term', t: 'step' },
      { l: 'View grades & GWA', t: 'success' },
    ],
    warn: 'Grades are hidden until BOTH conditions are met: all SET evaluations done AND admin enables grade release.',
    dos: ['Complete evaluations as soon as the SET window opens', 'Screenshot your grades for your personal records', 'Report any grade discrepancies to OCS immediately'],
    donts: ["Don't ask faculty directly about your grade — use the portal", "Don't wait to do evaluations if you need grades urgently", "Don't ignore grade discrepancies — report them within the reconsideration window"],
  },
  {
    title: 'Plan of Study',
    sub: 'Track your degree program course-by-course progress.',
    accent: '#7f1d2e', illu: 'plan',
    steps: ['Go to Plan of Study.', 'View required courses organized by year level and semester.', 'Green checkmarks = passed; yellow = in progress; grey = not yet taken.', 'When all requirements are met, the Apply for Graduation button becomes available.'],
    flow: [
      { l: 'Open Plan of Study', t: 'start' },
      { l: 'View course grid', t: 'step' },
      { l: 'Check completion status', t: 'step' },
      { l: 'All required done?', t: 'decision' },
      { l: 'Apply for Graduation', t: 'success' },
    ],
    warn: 'The plan of study reflects your official curriculum. Contact OCS if courses appear missing or incorrect.',
    dos: ['Review your plan of study every term to stay on track', 'Enlist in courses listed in your current year/semester', 'Use the plan to identify remaining requirements before graduation'],
    donts: ["Don't ignore courses shown as incomplete in your plan", "Don't assume elective courses are optional without checking your curriculum", "Don't apply for graduation without reviewing your plan first"],
  },
  {
    title: 'Specialization',
    sub: 'Apply for a degree track or specialization within your program.',
    accent: '#92400e', illu: 'consents',
    steps: ['Go to Specialization (only available if your program has tracks).', 'Click the specialization track you want and review its required courses.', 'Select your planned specialization courses for each semester.', 'Click Apply — OCS will review and notify you of their decision.'],
    flow: [
      { l: 'Open Specialization', t: 'start' },
      { l: 'Browse available tracks', t: 'step' },
      { l: 'Select and review track', t: 'step' },
      { l: 'Submit application', t: 'step' },
      { l: 'OCS approves/denies', t: 'success' },
    ],
    warn: 'Once approved, your specialization track is locked. Changing it later requires OCS approval.',
    dos: ['Choose a specialization that aligns with your career goals', 'Review all required courses for the track before applying', 'Apply early to ensure sections are available'],
    donts: ["Don't apply for a specialization just based on course availability", "Don't apply if you haven't completed the listed prerequisites", "Don't submit multiple specialization applications"],
  },
  {
    title: 'SET — Faculty Evaluation',
    sub: 'Evaluate your faculty to unlock your grades for the term.',
    accent: '#7f1d2e', illu: 'evaluation',
    steps: ['Go to SET when the FIC (Faculty-in-Charge) evaluation window is open.', 'Click each faculty member listed to open their evaluation form.', 'Rate all questions on the scale of 1–5 and add optional written comments.', 'Submit each form — once all faculty are evaluated, your grades are unlocked.'],
    flow: [
      { l: 'FIC window opens', t: 'start' },
      { l: 'Open SET module', t: 'step' },
      { l: 'Evaluate each faculty', t: 'step' },
      { l: 'All faculty done?', t: 'decision' },
      { l: 'Grades unlock', t: 'success' },
    ],
    warn: 'You CANNOT view grades until ALL faculty evaluations are submitted. There are no exceptions.',
    dos: ['Be honest and constructive in your evaluations', 'Complete all evaluations as soon as the window opens', 'Read each question carefully before rating'],
    donts: ["Don't submit all 5s or all 1s without reading the questions — this skews institutional data", "Don't skip evaluation just because you expect high grades", "Don't let the window close without completing all evaluations"],
  },
  {
    title: 'My Profile',
    sub: 'View your personal and academic information.',
    accent: '#92400e', illu: 'profile',
    steps: ['Go to My Profile.', 'View name, student number, program, college, year level, and academic standing.', 'Check cumulative GWA, total units completed, and academic status (Good Standing, etc.).', 'To request corrections, contact Admin. Change your password from this page.'],
    flow: [
      { l: 'Open My Profile', t: 'start' },
      { l: 'View personal details', t: 'step' },
      { l: 'Check academic standing', t: 'step' },
      { l: 'Data incorrect?', t: 'decision' },
      { l: 'Contact Admin for correction', t: 'step' },
    ],
    warn: 'You CANNOT edit your own academic information. All corrections must be made by the Admin.',
    dos: ['Verify your profile details at the start of each term', 'Change your password regularly for account security', 'Report name or student number errors to Admin immediately'],
    donts: ["Don't share your portal login credentials with anyone", "Don't attempt to edit academic data — only Admin can do this", "Don't ignore inaccurate GWA — report it to OCS"],
  },
  {
    title: 'Appeal to Enlist (PD)',
    sub: 'Submit a formal appeal if you have a Permanent Disqualification.',
    accent: '#7f1d2e', illu: 'banner',
    steps: ['Go to Banner Requests → Appeal to Enlist with Permanent Disqualification.', 'Fill in your student number, full name, term, and detailed grounds for appeal.', 'Attach all required supporting documents (letters, certificates, etc.).', 'Submit — OCS will review, consult with the Dean/Registrar, and notify you of the decision.'],
    flow: [
      { l: 'Open PD Appeal form', t: 'start' },
      { l: 'Fill in details & grounds', t: 'step' },
      { l: 'Attach documents', t: 'step' },
      { l: 'Submit appeal', t: 'step' },
      { l: 'Await OCS/Dean decision', t: 'success' },
    ],
    warn: 'PD appeals are reviewed at the highest institutional level. Incomplete or unsubstantiated appeals are denied.',
    dos: ['Provide strong, documented grounds for your appeal', 'Attach all required supporting documents', 'Submit early — review takes time and involves multiple offices'],
    donts: ["Don't submit without consulting with your academic adviser first", "Don't submit incomplete documents — your appeal will be denied", "Don't submit multiple appeals for the same disqualification"],
  },
  {
    title: 'Request for Late Enrollment',
    sub: 'Request enrollment after the regular enrollment window has closed.',
    accent: '#1e5c3a', illu: 'banner',
    steps: ['Go to Banner Requests → Request for Late Enrollment.', 'Enter your name, student number, term, intended course load, and reason for lateness.', 'Upload supporting documents (medical certificate, emergency letter, etc.).', 'Submit — OCS reviews the request; if approved, they process your enrollment directly.'],
    flow: [
      { l: 'Open Late Enrollment form', t: 'start' },
      { l: 'Fill in reason & load', t: 'step' },
      { l: 'Upload supporting docs', t: 'step' },
      { l: 'Submit request', t: 'step' },
      { l: 'OCS approves & enrolls', t: 'success' },
    ],
    warn: 'Late enrollment requests may incur additional fees. Check with the Registrar before submitting.',
    dos: ['Submit your request as early as possible after missing the window', 'Provide legitimate and verifiable reasons', 'Include all required documents in one submission'],
    donts: ["Don't submit without proper supporting documentation", "Don't assume approval — wait for OCS confirmation before attending classes", "Don't submit after the late enrollment window has closed"],
  },
  {
    title: 'Change / Add / Drop (DRP)',
    sub: 'Request to change sections, add subjects, or drop subjects.',
    accent: '#92400e', illu: 'banner',
    steps: ['Go to Banner Requests → Change/Add/Drop (window must be open).', 'Select request type: Change section, Add a subject, or Drop a subject.', 'Fill in relevant details: current enrollment, target section/subject, and reason.', 'Submit — OCS will review and update your enrollment accordingly.'],
    flow: [
      { l: 'Open Change/Add/Drop form', t: 'start' },
      { l: 'Select request type', t: 'step' },
      { l: 'Fill in details & reason', t: 'step' },
      { l: 'Submit request', t: 'step' },
      { l: 'OCS updates enrollment', t: 'success' },
    ],
    warn: 'A DROP (DRP) grade will permanently appear on your TOR for any dropped subject. Think carefully before dropping.',
    dos: ['Confirm the change/drop window is open before submitting', 'Submit only for genuine academic reasons', 'Discuss with your adviser before dropping required subjects'],
    donts: ["Don't drop a required course without your adviser's guidance", "Don't submit a change/drop request outside the official window", "Don't drop subjects on impulse — DRP grades are permanent"],
  },
];

/* ─── DEPT HEAD ──────────────────────────────────────────────── */
const DEPT_HEAD: TModule[] = [
  {
    title: 'Dashboard',
    sub: 'Overview of your department\'s consents, courses, and sections.',
    accent: '#6b21a8', illu: 'dashboard',
    steps: ['Log in as Department Head.', 'View stat cards: pending consents, active sections, and department courses.', 'A yellow alert appears if consent requests need immediate attention — act promptly.', 'Use Quick Action buttons for fast navigation to key modules.'],
    flow: [
      { l: 'Dept Head logs in', t: 'start' },
      { l: 'Dashboard loads', t: 'step' },
      { l: 'Pending consents?', t: 'decision' },
      { l: 'Go to Dept Consent', t: 'step' },
      { l: 'Review section data', t: 'success' },
    ],
    warn: 'Unanswered consent requests block students from enlisting. Process them within 24 hours.',
    dos: ['Check the dashboard at least once daily during enlistment', 'Act on pending consents before they expire', 'Monitor section enrollment for your department\'s courses'],
    donts: ["Don't ignore yellow consent alerts on the dashboard", "Don't process consents for courses outside your department", "Don't use the dashboard stats for official reports — data is approximate"],
  },
  {
    title: 'Dept Consent',
    sub: 'Approve or deny departmental consent requests for your courses.',
    accent: '#7f1d2e', illu: 'consents',
    steps: ['Go to Dept Consent. All pending requests for your department\'s courses appear here.', 'Click a request to view the student name, target course, section, and reason.', 'Verify the student meets any departmental requirements for the course.', 'Click Approve (student can now enlist) or Deny with a clear reason.'],
    flow: [
      { l: 'Student submits dept consent', t: 'start' },
      { l: 'Dept Head reviews', t: 'step' },
      { l: 'Student meets requirements?', t: 'decision' },
      { l: 'Approve → student enlists', t: 'success' },
      { l: 'Deny with reason', t: 'reject' },
    ],
    warn: 'Approving a dept consent allows enlistment but does NOT guarantee the student gets a slot — sections may fill up.',
    dos: ['Review each request carefully against departmental requirements', 'Approve promptly to avoid delaying student enrollment', 'Provide actionable feedback when denying'],
    donts: ["Don't approve consents for full sections", "Don't deny without a stated reason", "Don't process requests for courses outside your department"],
  },
  {
    title: 'Sections',
    sub: 'Monitor sections for your department\'s courses (view only).',
    accent: '#6b21a8', illu: 'table',
    steps: ['Go to Sections.', 'View all sections for your department\'s courses in the current term.', 'Review schedule, assigned faculty, room, and current enrollment per section.', 'For any scheduling changes, contact OCS directly — this page is read-only.'],
    flow: [
      { l: 'Open Sections', t: 'start' },
      { l: 'View section list', t: 'step' },
      { l: 'Check schedule & faculty', t: 'step' },
      { l: 'Issue found?', t: 'decision' },
      { l: 'Contact OCS', t: 'step' },
    ],
    warn: 'This page is VIEW-ONLY. You cannot edit sections here. Contact OCS for any changes.',
    dos: ['Monitor section enrollment throughout the term', 'Report scheduling conflicts to OCS early', 'Verify faculty assignments match department assignments'],
    donts: ["Don't assume this page allows editing — all changes go through OCS", "Don't monitor sections outside your department", "Don't wait until the end of term to report scheduling issues"],
  },
  {
    title: 'Courses',
    sub: 'Add and manage courses for your department.',
    accent: '#7f1d2e', illu: 'form',
    steps: ['Click Add Course.', 'Fill in course code, type (lecture/lab), title, units, year level, and consent flags.', 'Add prerequisites and corequisites if required by the curriculum.', 'Click Save — OCS can now create sections for this course each term.'],
    flow: [
      { l: 'Open Courses', t: 'start' },
      { l: 'Click Add Course', t: 'step' },
      { l: 'Fill details & flags', t: 'step' },
      { l: 'Add prerequisites', t: 'step' },
      { l: 'Save course', t: 'success' },
    ],
    warn: 'Course codes must match the official curriculum. Duplicates or incorrect codes affect student plan-of-study tracking.',
    dos: ['Use the official course code from the approved curriculum', 'Set consent flags according to faculty or department policy', 'Always set prerequisites for advanced courses'],
    donts: ["Don't create courses without verifying against the official curriculum", "Don't change course units after students have enrolled", "Don't leave year level blank"],
  },
];

/* ─── Export ─────────────────────────────────────────────────── */
export const TUTORIAL_DATA: Record<Role, TModule[]> = {
  admin: ADMIN,
  ocs: OCS,
  faculty: FACULTY,
  student: STUDENT,
  department_head: DEPT_HEAD,
};
